[[collection]]
type = "art"
img = "/img/iisc_poster.png"
title = "An IR for Distributed Heterogeneous Computing"
link = "https://events.csa.iisc.ac.in/csworkshop2025/"
subtitle = "Computer Systems Workshop 2025"
content = "This work introduces DHIR, an MLIR-based intermediate representation designed to unify distributed and heterogeneous execution. DHIR enables task parallelism, device placement, and communication within a single abstraction, improving programmability and compiler optimization across CPUs, GPUs, and clusters."



[[collection]]
type = "art"
img = "/img/pldi_src.png"
title = "An IR for Distributed Heterogeneous Computing"
link = "https://pldi25.sigplan.org/track/pldi-2025-src"
subtitle = "PLDI SRC 2025"
content = "This work introduces DHIR, an MLIR-based intermediate representation designed to unify distributed and heterogeneous execution. DHIR enables task parallelism, device placement, and communication within a single abstraction, improving programmability and compiler optimization across CPUs, GPUs, and clusters."

