[[collection]]
type = "art"
img = "/img/pldi_src.png"
title = "The Old Man and the Sea"
link = "https://example.com"
subtitle = "[American] Ernest Hemingway"
content = "A novella that tells the story of Santiago, an aging Cuban fisherman who struggles with a giant marlin far out in the Gulf Stream. The story is a tale of endurance, perseverance, and the human spirit's struggle against nature. It explores themes of courage, pride, and the relationship between man and the natural world."
footer = "⭐︎⭐︎⭐︎⭐︎⭐︎"

